name: Build and upload artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile for ${{ matrix.target }}
        run: cargo build --target ${{ matrix.target }}

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: udp_port_analyzer_${{ matrix.target }}
          path: target/${{ matrix.target }}/debug/udp-port-analyzer.exe


